### ISSUE TITLE
GCP access token seems invalid / not refreshed after long running build

### ISSUE THREAD

**Issue by klyse** [hashicorp/packer-plugin-googlecompute#206] opened 2024-01-25 12:10 UTC
#### Overview of the Issue

I have a packer windows build that gets orchestrated with ansible. If ansible takes a loong time (1h+) and fails in the last steps, the packer instance cannot be deleted because the GCP access token seems invalid / not refreshed.

#### Reproduction Steps

Create a long running packer build with ansible provisioner. Run it. Create a failing step at least 1h runtime.

```hcl
packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
    ansible = {
      version = "~> 1"
      source  = "github.com/hashicorp/ansible"
    }
  }
}

source "googlecompute" "gcp" {
  project_id          = "xxx"
  source_image        = "windows-server-2022-dc-v20240111"
  zone                = "europe-west1-c"
  machine_type        = "n1-standard-4"
  accelerator_type    = "projects/xxx/zones/europe-west1-c/acceleratorTypes/nvidia-tesla-t4-vws"
  accelerator_count   = 1
  on_host_maintenance = "TERMINATE"
  disk_size           = 50

  image_name = "${lower(local.image_name)}-${local.timestamp}"
  image_family = "windows-server"
  image_description = "xx"
  image_labels = {
    server_type = "windows-2022"
  }

  communicator   = "winrm"
  winrm_username = "Packer"
  winrm_use_ssl  = true
  winrm_insecure = true
  winrm_timeout  = "30m"

  metadata = {
    windows-startup-script-ps1 = file("${path.root}/scripts/ec2-user-data.ps1")
  }
}
```

### Plugin and Packer version

From `packer version`: 1.10.0

### Operating system and Environment details

Tried with:
* MacOS Sonoma (M1 Max)
* Debian 12 based docker container

### Log Fragments and crash.log files

```
==> googlecompute.gcp: Provisioning step had errors: Running the cleanup provisioner, if present...
2024/01/25 11:33:17 packer-plugin-googlecompute_v1.1.4_x5.0_linux_amd64 plugin: 2024/01/25 11:33:17 Skipping cleanup of IAP tunnel; "iap" is false.
==> googlecompute.gcp: Deleting instance...
==> googlecompute.gcp: 
==> googlecompute.gcp: Error deleting instance. Please delete it manually.
==> googlecompute.gcp: Name: packer-65b2391b-176f-ce08-4a5c-b678a6aa0f2d
==> googlecompute.gcp: Error: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
==> googlecompute.gcp: 
==> googlecompute.gcp: Details:
==> googlecompute.gcp: [
==> googlecompute.gcp:   {
==> googlecompute.gcp: Name: packer-65b2391b-176f-ce08-4a5c-b678a6aa0f2d
==> googlecompute.gcp:     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
==> googlecompute.gcp:     "domain": "googleapis.com",
==> googlecompute.gcp:     "metadatas": {
==> googlecompute.gcp:       "method": "compute.v1.InstancesService.Delete",
==> googlecompute.gcp:       "service": "compute.googleapis.com"
==> googlecompute.gcp:     },
==> googlecompute.gcp:     "reason": "ACCESS_TOKEN_EXPIRED"
==> googlecompute.gcp:   }
==> googlecompute.gcp: ]
==> googlecompute.gcp: 
==> googlecompute.gcp: More details:
==> googlecompute.gcp: Reason: authError, Message: Invalid Credentials
==> googlecompute.gcp: Error: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
==> googlecompute.gcp:
==> googlecompute.gcp: Details:
==> googlecompute.gcp: [
==> googlecompute.gcp:   {
==> googlecompute.gcp:     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
==> googlecompute.gcp:     "domain": "googleapis.com",
==> googlecompute.gcp:     "metadatas": {
==> googlecompute.gcp:       "method": "compute.v1.InstancesService.Delete",
==> googlecompute.gcp:       "service": "compute.googleapis.com"
==> googlecompute.gcp:     },
==> googlecompute.gcp:     "reason": "ACCESS_TOKEN_EXPIRED"
==> googlecompute.gcp:   }
==> googlecompute.gcp: ]
==> googlecompute.gcp: 
==> googlecompute.gcp: More details:
==> googlecompute.gcp: Reason: authError, Message: Invalid Credentials
==> googlecompute.gcp:
    googlecompute.gcp: Instance has been deleted!
==> googlecompute.gcp: Deleting disk...
==> googlecompute.gcp: 
==> googlecompute.gcp: Name: packer-65b2391b-176f-ce08-4a5c-b678a6aa0f2d
==> googlecompute.gcp: Error deleting disk. Please delete it manually.
==> googlecompute.gcp: Error: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
==> googlecompute.gcp: Details:
==> googlecompute.gcp: 
==> googlecompute.gcp: [
==> googlecompute.gcp:   {
==> googlecompute.gcp:     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
==> googlecompute.gcp:     "domain": "googleapis.com",
==> googlecompute.gcp: Name: packer-65b2391b-176f-ce08-4a5c-b678a6aa0f2d
==> googlecompute.gcp:     "metadatas": {
==> googlecompute.gcp:       "method": "compute.v1.DisksService.Delete",
==> googlecompute.gcp:       "service": "compute.googleapis.com"
==> googlecompute.gcp:     },
==> googlecompute.gcp:     "reason": "ACCESS_TOKEN_EXPIRED"
==> googlecompute.gcp:   }
==> googlecompute.gcp: ]
==> googlecompute.gcp: 
==> googlecompute.gcp: More details:
==> googlecompute.gcp: Reason: authError, Message: Invalid Credentials
==> googlecompute.gcp:
==> googlecompute.gcp: Error: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
==> googlecompute.gcp: Details:
==> googlecompute.gcp: [
==> googlecompute.gcp:   {
==> googlecompute.gcp:     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
==> googlecompute.gcp:     "domain": "googleapis.com",
==> googlecompute.gcp:     "metadatas": {
==> googlecompute.gcp:       "method": "compute.v1.DisksService.Delete",
==> googlecompute.gcp:       "service": "compute.googleapis.com"
==> googlecompute.gcp:     },
2024/01/25 11:33:18 [INFO] (telemetry) ending googlecompute.gcp
==> googlecompute.gcp:     "reason": "ACCESS_TOKEN_EXPIRED"
==> googlecompute.gcp:   }
==> googlecompute.gcp: ]
==> googlecompute.gcp: 
==> googlecompute.gcp: More details:
==> googlecompute.gcp: Reason: authError, Message: Invalid Credentials
==> googlecompute.gcp:
    googlecompute.gcp: Disk has been deleted!
Build 'googlecompute.gcp' errored after 59 minutes 12 seconds: Error executing Ansible: Non-zero exit status: exit status 2
==> Wait completed after 59 minutes 12 seconds
2024/01/25 11:33:18 machine readable: error-count []string{"1"}
```

**Comment by lbajolet-hashicorp** [comment] 2024-02-02 20:36
Hi @klyse,

Thanks for the report. I'll try to look into it soon, but from the logs you shared I cannot see how you're authenticating with GCE, is there a way you can share that?

If you're using an `access_token`, the problem you're encountering is expected, as Packer will not (cannot even) refresh it, as it was produced out-of-band.
As for the other possibilities for authentication, I would expect the GCE SDK to be able to refresh the credentials if needed, but there might be some option that we need to set or possibly forgot in some place, I'll try to dig into that code and see what we can do here.

Also I noticed our docs regarding authentication weren't being included anymore since we updated them last year with #186, so thank you for helping us notice that :)

**Comment by klyse** [comment] 2024-02-04 09:35
Hi @lbajolet-hashicorp, thanks for the answer. I'm authenticating through the `GOOGLE_APPLICATION_CREDENTIALS` env var that points to a file with the GCP service account.
I now have a workaround with a much faster vm to ensure not to exceed the access token cap I was experiencing

**Comment by lbajolet-hashicorp** [comment] 2024-02-05 21:00
Hi @klyse,

Thanks for the update, glad you found a workaround.
I'm not able to reproduce the problem with a long-running build, and a service account key; I presume the GCP SDK is doing the right thing in my context, and refreshing the ticket as expected.

Since you've found a way to circumvent the issue, and given I can't reproduce the problem locally, I'll close this issue for now.
If you experience the problem again, feel free to reopen, and we can investigate this some more.

**Closed by lbajolet-hashicorp** 2024-02-05 21:00 UTC
Labels: bug, sync to jira

**Comment by ae07177** [comment] 2024-10-01 17:40
I am having the exact same issue with windows2022 build where the sysprep takes lots of time, i am using externalId federation to authenticate from AWS to GCP using service account. 
However it appears that the default session duration is 1hr , I have to tried to extend it by updating the "iam.allowServiceAccountCredentialLifetimeExtension" org policy  to 2hours, inspite of that  token expires midway and packer cannot refresh it :(
